### ISSUE TITLE
Add Document

### ISSUE THREAD

**Issue by AbdelrahmanDwedar** [Sadullah-TANRIKULU/django_drinks_api#1]
I'm interested in using the API for testing some stuff, but when I checked the repository I found no README.md file explaining how to use it.

I probably going to explore the code and figure it put myself, but generally talking you might have to add one to make ir more accessible to non-Django developers like front-end developer etc...
Even if it's simple it deserve to be cared of, who knows, it might turn into amazing SaaS project one day.

**Comment by Sadullah-TANRIKULU** [comment]
Thanks for feedback, i'll fix it soon 👍🏿 😃

**Comment by AbdelrahmanDwedar** [comment]
No problem

If you got some free time I might make that docs push it as pull request too

**Comment by Sadullah-TANRIKULU** [comment]
I invited you to collaborate with me. Now I'm working on SAP ABAP development, I don't have enough time. If you want, you can push some stuff. 👍🏽
